# Generated by Django 4.1 on 2022-10-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
