# Generated by Django 4.1 on 2022-10-29 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='amount_of_donation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
