# Generated by Django 4.1 on 2022-11-02 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(38)],
                    ),
                ),
                ("date_created", models.DateField()),
                ("date_expired", models.DateField()),
                ("money_accumulated", models.IntegerField(default=0)),
                ("money_needed", models.IntegerField(default=0)),
                ("image_url", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
