# Generated by Django 4.1 on 2022-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
